### PR TITLE
Fixed DisableDropSound in parser/filters.

### PR DESCRIPTION
**Pull request by TehCheat**

### CODE REVIEW

**Comment by TehCheat** [comment]
Is there a way to bump the NuGet build?

**Comment by TehCheat** [comment]
Also, the new filter info is coming out in ~10 hours, so it's not a big deal if this doesn't get in its own NuGet build.

**Comment by smad2005** [comment]
https://www.nuget.org/packages/PoeFilterParser/1.0.34

**Comment by smad2005** [comment]
Sorry for waiting seems like appveyor deployment is broken (temporary)

**Pull request merged**
